### ISSUE TITLE
Inspections Photos - Not viewable

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#10]
The system shows the photo count associated to an inspection but does not display the photo when user clicks on the photo link.

**Comment by mohsinkar** [comment]
The data is not available on the KCI dev so link will show file not found error 
the requirements were to open links in new tab

**Comment by ladejobi** [comment]
I'll test in SHA Dev

**Comment by ladejobi** [comment]
Tested and validated in KCI Dev
