### ISSUE TITLE
Delete New SWMFAC Record - Error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#100]
The system does not delete new records created by user. It allows user to execute the delete workflow but does not remove the record from the UI.
To replicate 
1. Create a new SWMFAC
2. Delete the SWMFAC record

**Comment by TaraF** [comment]
@ladejobi  -- can you confirm this is happening for any delete?  I think this was marked as an issue before.  If that is happening in KCI dev, Mohsin should be able to fix.

**Comment by ladejobi** [comment]
@TaraF i'm unable to replicate the issue in KCI Dev due the the web map issue however it isn't happening in production. I was able to delete new records without an issue in prod.

**Comment by TaraF** [comment]
@mohsinkar -- passing this over to you as it is a flex issue. Services are all working and everything is going through fine.  (you can now test in KCI dev!)

**Comment by ladejobi** [comment]
@mohsinkar did you fix the issue in KCi Dev? I wasn't able to replicate the error here.

**Comment by ladejobi** [comment]
Issue fixed in KCi dev, will test to confirm fix in SHA dev
