### ISSUE TITLE
Import Workflow - Error 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#101]
The system consistently returns an error when user executes the import workflow and clicks on the finish button to complete the import. 

![image](https://user-images.githubusercontent.com/8458252/36694067-26fa75c2-1b0b-11e8-9162-df96f0662ab4.png)

**Comment by TaraF** [comment]
@ladejobi  has this been tested in KCI dev since the schema updates?

**Comment by ladejobi** [comment]
Yes, but recall KCI Dev didn't have a contract associated for the import so I never could fully test it there but it was working fine in SHA dev prior to the schema update.

**Comment by ladejobi** [comment]
@mohsinkar the Import function is no longer working as it was in KCI Dev. It was working fine prior to the web content been fixed. Can you look into it at KCI dev while Tara investigates the error in SHA Dev?

![image](https://user-images.githubusercontent.com/8458252/36921288-c887db04-1e31-11e8-9596-efb5c26392a0.png)

**Comment by TaraF** [comment]
@ladejobi  -- I tested this out in KCI dev. It appears to be working fine (there is a missing contract in data as previously noted) but if you Add a New Contract, and put in test data, it will create the swmfac -- no problem.

**Comment by ladejobi** [comment]
@mohsinkar @TaraF this issue is still no longer happening in KCI but occurring in SHA dev. I want to confirm the fix(if any) will resolve SHA dev when we push.

**Comment by mohsinkar** [comment]
@TaraF @ladejobi if this is working in KCI Dev than we need to make same updates in SHA

**Comment by ladejobi** [comment]
@TaraF lets make sure you push any fix made in KCI for this bug to SHA dev.

**Comment by ladejobi** [comment]
Bug fixed
