### ISSUE TITLE
Add Worklow - data error 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#102]
The system inconsistent returns a data not saved error when user executes the add SWMFAC workflow and clicks on the finish button. The error is not consistent, system sometimes work as expected. I was unable to isolate the cause of the error.

![image](https://user-images.githubusercontent.com/8458252/36694142-6dc764d8-1b0b-11e8-804a-90b8e058a7e6.png)

**Comment by TaraF** [comment]
@ladejobi  -- again unable to replicate error.  I was able to add several without a problem in SHA dev.

Again, thinking this is not a viable bug, unless someone can provide step by step (with values etc) to replicate the issue.

**Comment by ladejobi** [comment]
@TaraF I think this issue will be fixed once bug#101 is resolved. Same issue but the other bug has a more isolated process for the error

**Comment by ladejobi** [comment]
@mohsinkar I'm encountering this error in KCI dev.  You may need to do a couple of add SWMFAC workflows to replicate the error. Can you look into it while Tara investigates SHA dev?

![image](https://user-images.githubusercontent.com/8458252/36921453-6f01be8c-1e32-11e8-8aa1-228fd481e128.png)

**Comment by TaraF** [comment]
@ladejobi  -- I think we need more information from the testing here.  It seems like you are generating that error based on a specific value you are selecting or inputing, as I cannot replicate.  Do you have a log of what values you input when you are getting the error? 

@mohsinkar -- based on the error, do you have any indication in the flex code what could be wrong?

**Comment by ladejobi** [comment]
@TaraF i wasn't able to isolate the error to a specific value entered. It seems to occur after user adds multiple SWMFACs, i.e on the 2nd, 3rd or 4th record added.

**Comment by mohsinkar** [comment]
@TaraF Can you check what does this service return? http://vm-adwdev/NpdesServices/AddSWMFAC


When the AddSWMFAC display an error message it is getting  “False” value 
<Success>String content</Success>

**Comment by TaraF** [comment]
provided successful fiddler call as example via email

**Comment by ladejobi** [comment]
Bug fixed verified in KCI Dev @TaraF can you deploy to SHA dev?

**Comment by TaraF** [comment]
deployed to SHA dev

**Comment by ladejobi** [comment]
Bug fixed
