### ISSUE TITLE
Gen Tab - Edit workflow - Update By and Date Fields- Not updated

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#104]
@mohsinkar  In the Gen Tab the system does not update the Last update By and Last Update date fields when user commits an edit. Issue is been encountered in KCI DEV .

**Comment by ladejobi** [comment]
Tara,

Can you check this following service what field names and format you are expecting for the last edited by and last edited date 

I am currently passing userid and I think the last edit date is auto updated let me know if this is the wrong assumption. 

http://vm-adwdev/NpdesServices/UpdateSWMFAC

**Comment by TaraF** [comment]
sent email to @mohsinkar.  Not service related, believed to be flex. reassigning.

**Comment by ladejobi** [comment]
Bug fixed
