### ISSUE TITLE
KCI Dev- SWMFAC Sheet report down

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#106]
@TaraF the SWMFAC sheet report launched from the results tab is not working. Returns a blank report page. Suspect it's still pointing to the old instance. Dev and prod are working fine.

**Comment by TaraF** [comment]
@ladejobi -- this is working for me now.  It may have been down while Brendan was helping us with the server (vm-adwdev) issue.

**Comment by ladejobi** [comment]
@TaraF the report is still down for me. Are you launching from the report button in the results tab?

![image](https://user-images.githubusercontent.com/8458252/36999687-eb9e5186-208e-11e8-859d-a6821d3e4c36.png)

**Comment by TaraF** [comment]
@ladejobi -- yes I tried it on several random ones.  Is there one particular swmfac# that is not showing up for you?

**Comment by TaraF** [comment]
@ladejobi  working for everyone I have tested:  020217, 022216, 022217, 022218....

please give an example where it is failing.  thanks!

**Comment by ladejobi** [comment]
Report is working in IE
