### ISSUE TITLE
KCI Dev - Reserve SWMFAC - Not working

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#109]
@mohsinkar the Reserve SWMFAC function in KCI dev is no longer functional.

**Comment by mohsinkar** [comment]
@Tara i am calling this URL http://vm-adwdev/NpdesServices/GetNextSWMFACNums?County=01&browsernocache=Wed%20Mar%207%2010%3A32%3A07%20GMT%2D0500%202018&Limit=1&format=xml&UserId=KCI%5CMOHSIN%2EKARIM

Getting a 404 , has the location changed ?

**Comment by TaraF** [comment]
@mohsinkar  -- no, nothing has changed with this service. let me take a look, maybe something with schema updates is breaking it.  I will let you know what I find.

**Comment by ladejobi** [comment]
@TaraF any update on this bug

**Comment by TaraF** [comment]
this is fixed in KCI dev.  For some reason, after schema updates, NPDES.RESERVE_LOG_SWMFAC was no longer registered with the geodatabase (does not need to be registered as versioned).

**Comment by ladejobi** [comment]
Fix validated
