### ISSUE TITLE
ADD Workflow - Geometry errors

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#114]
@Tara bug #99 fixed in KCI Dev but still occuring in SHA dev
![image](https://user-images.githubusercontent.com/8458252/37221121-d26d8082-2396-11e8-8601-86f593eec909.png)

**Comment by ladejobi** [comment]
@TaraF issue is still happening in SHA Dev. I noticed it doesn't occur when user selects status = proposed. To replicate search new records i created today, 060660 and 151470.

Another issue i noticed is the system seems to be creating 2 features on the map when user selects Status =proposed. See the sample screenshot below for this test scenario

![image](https://user-images.githubusercontent.com/8458252/37347975-690220d8-26a9-11e8-8024-6d336339b396.png)

**Comment by TaraF** [comment]
This is fixed.  It had to do with the XML pointing to the wrong map service and layer id.  Please test in SHA DEV.

**Comment by ladejobi** [comment]
@TaraF that's good news! i'll test.

**Comment by ladejobi** [comment]
@TaraF was able to verify the fix but looks like the same map issue is happening on the import workflow. You may need to update the services there too. Search SWMFAC no. 2330335 i added via import. Below is the map error for that record. I also noticed after I delete a record the system does not remove the symbology from the map.
![image](https://user-images.githubusercontent.com/8458252/37362392-6d03162a-26cb-11e8-9fcf-2fd25aa29861.png)

**Comment by TaraF** [comment]
This is working as expecting.  Using the same file will generate the same geometry in the same location, unless you otherwise specify (by clicking the re-enable map tool -- and drawing new geometry).  What is happening above is you are stacking a bunch of geometries and the identify is only picking up the one on top.

**Comment by ladejobi** [comment]
Bug fixed
