### ISSUE TITLE
SHA DEV - Reserve SWMFAC 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#115]
The Reserve swmfac function on sha dev is throwing a server error for the report
![image](https://user-images.githubusercontent.com/8458252/37221177-08b06984-2397-11e8-9b30-1bfdbaf462eb.png)

**Comment by TaraF** [comment]
This is fixed in SHA dev. Please test. 

![temp](https://user-images.githubusercontent.com/4104464/37292375-bbb4deac-2608-11e8-965d-24b336dcfae9.PNG)

**Comment by ladejobi** [comment]
Bug fix validated in SHA dev
