### ISSUE TITLE
High Priority - SWMFAC Rating By County Report - Down

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#116]
@tara pls review  this high priority issue reported by Craig - SWMFAC Ratings by County report is down in production. I checked Dev and it's working there. It's not the same as the one you were working with Mark on, that report is working now.

**Comment by TaraF** [comment]
@ladejobi  This is actually working in production, it just takes a minute or so to come up.  This is a production server issue -- not much I can do on my end.  Please see screen captures -- and the run date at the bottom of report (today, 1130 am).

![swmfacreport1](https://user-images.githubusercontent.com/4104464/40244333-1b8154ea-5ab2-11e8-91bb-16a562ce487f.PNG)
![swmfacreport2](https://user-images.githubusercontent.com/4104464/40244334-1b908a64-5ab2-11e8-94e4-2b52b4bd6dd2.PNG)

**Comment by ladejobi** [comment]
@TaraF weird, it's working now. It was throwing an error when i tested and stakeholders sent screenshots with the same results. Ok, i'll let stakeholders know, hopefully it doesn't fail again.
