### ISSUE TITLE
High Prioirty - SWMFAC - Add Maint Record - Not working 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#117]
@TaraF here's another high priority from Craig - The  Add Maintenance record workflow is not working in production. The system is unresponsive after user completes form and clicks on the add button. This issue is happening in SHA Dev.

**Comment by TaraF** [comment]
@ladejobi  This is actually working in production, it just takes a minute or so to come up.  This is a production server issue -- not much I can do on my end.  Please see screen captures -- and the run date at the bottom of report (today, 1130 am).

![swmfacreport1](https://user-images.githubusercontent.com/4104464/40244333-1b8154ea-5ab2-11e8-91bb-16a562ce487f.PNG)
![swmfacreport2](https://user-images.githubusercontent.com/4104464/40244334-1b908a64-5ab2-11e8-94e4-2b52b4bd6dd2.PNG)

**Comment by TaraF** [comment]
InsertMaintRecord service call is returning 500 error.  Need to determine if things were changed in DB, or why this is suddenly failing. 

http://shagbwebd01/SWMFAC_ENH_API/api/Assets/InsertMaintRecord?p_FID=4b68e045-16eb-4062-88c9-327ee61f4156&p_RID=2055F755-A4C3-4A83-AAB3-AFC20C99DFCF&p_work_order_initiated=1&p_work_order_consultant=&p_work_order_int_date=05/14/2018 12:00:00&p_work_order_type=RETRO&p_hhd_approval_date=05/13/2018 12:00:00&p_work_order_permit_date=05/13/2018 12:00:00&p_maint_action_type=MINMAINT&p_hhd_comment=&p_maint_int_date=05/22/2018 12:00:00&p_contractor=&p_contract_number=&p_anticipated_completion=05/22/2018 12:00:00&p_date_complete=&p_engineer_est=&p_actual_const_cost=&p_constr_comment=&p_maint_status=CANCEL&p_sha_book=&p_create_date=05/18/2018 11:46:56&p_edit_date=05/18/2018 11:46:56&p_last_edit_by=SHACADD\TFEAGA

**Comment by TaraF** [comment]
@ladejobi  It looks like there is an additional GLOBALID field left on some of the feature classes/tables.  This was a problem before.  Please work with Kerry to remove and make sure items have been versioned again.  Two known tables at this time are:  BMP_MAINTENANCE and BMP_INSPECTION, but you should go through and make sure there aren't anymore.  I won't catch them until something breaks.   

This work needs to be done for SHA dev and SHA prod.

**Comment by ladejobi** [comment]
Issue resolved in dev and prod
