### ISSUE TITLE
Inspection Photos Display - Do not meet design Specifications

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#13]
The system does not display the photos in accordance with the design specified in the wire frames. Reference wireframes and update the photo below to display as designed. 
![image](https://user-images.githubusercontent.com/8458252/31024605-9df0c0ce-a50d-11e7-8031-eddf00e02382.png)

Also still show photo count function 
![image](https://user-images.githubusercontent.com/8458252/31024672-d2e9fb38-a50d-11e7-8e3e-1c96898e6ad5.png)

Retire the Zoom and Save icons

**Comment by mohsinkar** [comment]
open image in new browser tab on right click.

**Comment by ladejobi** [comment]
@mohsinkar there are still issues with the photo pop up. Use 030003 to test and replicate
1. The layout is too large. Make it large enough where the widget is still visible behind the photo (see sample below)
![image](https://user-images.githubusercontent.com/8458252/31253580-75d90638-a9f3-11e7-939a-a5e2fce78aeb.png)

2. The thumbnail below the photo should show all the photos, the system only displays one. Use oldest Inspection to replicate
3. The system does not show photo count 
4. The system does not allow user to open photo in a new browser  on right click or at all.

**Comment by ladejobi** [comment]
@mohsinkar @Tara (2) issues with the photos;
1. The system does not allow user to open photo in a new browser on right click or at all.
2. Can we make the image full screen within the pop up, now it's aligned to the left
![image](https://user-images.githubusercontent.com/8458252/32290654-224805ea-bf11-11e7-9ff5-ead30af659a7.png)

**Comment by mohsinkar** [comment]
@ladejobi the above example images are taken that way they were taken in a low vertical resolution layout that is why they show that way cornered .. if you look at other example the images show correctly. 
![image](https://user-images.githubusercontent.com/7361969/32299617-37b7f5da-bf24-11e7-9122-47d32fec1026.png)

Code is updated to include opening image in new browser window on click.

**Comment by ladejobi** [comment]
Verified photo image display is fine. Workflow for opening image in new browser window on click still not functional.

**Comment by TaraF** [comment]
@ladejobi  -- I walked through this and it seems to be functioning -- when you click on the main photo it does open up into a new tab.  Let me know if you were anticipating something different...

**Comment by ladejobi** [comment]
fix verified
