### ISSUE TITLE
General Tab - Attribute Not Updated

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#15]
The JPA field under the general tab should be a dropdown, based on the DOMAIN in the DB (no look up table). Reference requirement doc.  Please ask @TaraF if you have any questions.

**Comment by ladejobi** [comment]
@mohsinkar  domain update validated however system does not allow user to save an edit in the General Info tab. Returns an error pop up requesting user to enter all required fields despite those fields been populated. This error does not occur in production.
![image](https://user-images.githubusercontent.com/8458252/31124754-d3227202-a813-11e7-8137-b36ec1b55dc2.png)

**Comment by mohsinkar** [comment]
The new fields added are all required , For TMDL, JPA and 2 year fields.

@TaraF  please check the update service it is not returning the FacilityID and GlobalID after the update is called.

**Comment by ladejobi** [comment]
@TaraF
1, Lets add an * to the new fields that are required - TMDL, JPA and 2 year fields.
2. Despite the user populating all required fields the system still does not commit the changes to the database. retuens error below:
![image](https://user-images.githubusercontent.com/8458252/32291042-4424c9fe-bf12-11e7-9e48-7a15a8cbc7df.png)

**Comment by TaraF** [comment]
@mohsinkar  -- give this another try with new parameters I emailed you about.  Please reassign to me if services are still not working.

**Comment by ladejobi** [comment]
@mohsinkar is this fixed? I'm still encountering issue.

**Comment by ladejobi** [comment]
While completing #30 ( changes to the required fields), confirm the Save error is not reoccurring.

**Comment by TaraF** [comment]
@mohsinkar  -- reassigning to you as related to #30.  should just be confirmation it is working when you are done.

**Comment by ladejobi** [comment]
Issues been resolved under #30
