### ISSUE TITLE
Inspection Tab - Need aesthetics update

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#16]
The layout of the Inspection tab is a bit unorganized. Can you realign and clean up the labels, buttons and table to be organized. Also put some space/demarcation between the rating and Inspection sections. You can mirror the wireframe, see below:

![image](https://user-images.githubusercontent.com/8458252/31025289-1ca6af12-a510-11e7-97db-4a9f37b0a893.png)

**Comment by mohsinkar** [comment]
1. Aligned the grids
2. Fixed Inspection type text
Adding vertical bar making grids smaller making the labels not able to display in single line.

**Comment by ladejobi** [comment]
UI update will suffice.
