### ISSUE TITLE
SWMFAC Rating per county report - Update display

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#18]
As requested by stakeholder update the SWMFAC Rating per county report to always display header when user view report results.

**Comment by ladejobi** [comment]
1. Report is not returning any values when generated despite records been present in the filter selected.- Replicate with Fredrick, Rating III - Test record 100005 should show up
2. Rating of NR missing from the table 
3. Requirement not met. PDF view would have been a good around however there are issues with the PDF view. Header name/Title and table broken into pages.

![image](https://user-images.githubusercontent.com/8458252/32327598-73b4ce1c-bfad-11e7-8641-7bde7de98584.png)

**Comment by TaraF** [comment]
@ladejobi  -- all are fixed.  Please keep in mind for #1 above, I had to ask Mohsin to fix the flex side on inserting a rating record to include the facility id.  For the example you have, facility id was never captured, and I need that to pull the records correctly from the table.  Any new ratings added now should be seen.  If you have any questions, please let me know.

**Comment by ladejobi** [comment]
Issue 2 fixed. Issue 1 and 3 is still persisting.

**Comment by ladejobi** [comment]
Update report to filter data returned by:
 

-  Facility status = Existing
- Owner Name = SHA owned (including joint SHA fields, wild card that includes anything that has ‘SHA’)
- Year = Latest year rating

**Comment by TaraF** [comment]
original issues fixed: 1 (showing data now) and 3 (PDF working as expected). 

additionally, filters were added as described above for data.

please test.

**Comment by ladejobi** [comment]
fixed and tested

**Comment by ladejobi** [comment]
The system does not persist edits committed on the rating tab and thereby does not update the Rating field in the maintenance tab when user inputs a Rating Date in the Insp/Rating tab. Repliacte with 030005
