### ISSUE TITLE
UI Field Updates - Remove fields

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#20]
The system should no longer show the fields in the table below on the UI @mohsinkar please confirm this has been done.
![image](https://user-images.githubusercontent.com/8458252/32276531-d364a4ea-bee5-11e7-9f6b-8386dcb666ac.png)

**Comment by ladejobi** [comment]
UI has not been updated: 

1. @TaraF kiona wants us to show (No.2) field above. Requested we show it as “MDOT SHA Response Needed” - maximum character length.

2.Remove field below from Contract tab 
![image](https://user-images.githubusercontent.com/8458252/32293040-4d6b01d0-bf18-11e7-9ffa-2ce5a7d77a2b.png)

**Comment by ladejobi** [comment]
Disregard the #2 request- may be relevant for widget viewers.

**Comment by TaraF** [comment]
This is fixed, please test KCI dev.

**Comment by ladejobi** [comment]
Fix tested and verified
