### ISSUE TITLE
Add Function - Not working

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#21]
The add workflow is not working in KCI Dev. Let look at this and make sure we don't break something when we deploy to production.

**Comment by ladejobi** [comment]
Verify this is not an issue when e deploy to SHA Dev

**Comment by ladejobi** [comment]
This is an issue in SHA DEV. System returns an IO error after user commits a new SWMFAC to the database. Issue is not occurring in Production.

**Comment by ladejobi** [comment]
The system does not allow user complete an Add SWMFAC workflow and edit SWMFAC general info workflow

**Comment by TaraF** [comment]
@mohsinkar  service is successfully working now.  please see email with successful fiddler session.

**Comment by ladejobi** [comment]
Add workflow verified in SHA DEV. Encountered certain data pop up messages I'm not 100% sure is applicable to workflow. Will have Kerry test to confirm.

**Comment by ladejobi** [comment]
Workflow validated by kerry
