### ISSUE TITLE
SHA Rating Field - Incorrect domain values 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#22]
The values in the LU for the SHA rating field does not match the requirement specs. update to match table below.
![image](https://user-images.githubusercontent.com/8458252/32292043-3182977e-bf15-11e7-84a5-eb7700ee9963.png)

**Comment by mohsinkar** [comment]
this is resolved, updated the Domains table

**Comment by ladejobi** [comment]
Fix validated. Thanks @mohsinkar
