### ISSUE TITLE
New Field-BMP Inspection Type- Missing from UI

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#23]
The system does not show the new BMP Inspection Type field.

 Here is the comments from Tara regarding the build "***BMP_INSPECTION- INSPECTION_TYPE_ID (field has been updated to text to accommodate their Domain in DB – you will probably need to update in flex and also the ALL_DOMAINS table, their values in domain have been updated)**"

"

**Comment by mohsinkar** [comment]
![image](https://user-images.githubusercontent.com/7361969/32299361-5c326112-bf23-11e7-8813-5d59b150440c.png)

This is added in the UI as a text field since it is not editable, no data is displayed as records are null

**Comment by TaraF** [comment]
This is fixed, please test KCI dev.

**Comment by ladejobi** [comment]
Bug fixed and verified
