### ISSUE TITLE
SWMFAC Details by County and Rating Report - Issues

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#26]
There are (3) issues with report - 
 I. Update field to 
 - **Facility Designation** 
 - **Date of most recent Inspection**
 - **Most Recent SHA Rating Date**

2.Reports are not returning any values when generated despite records been present in the filter selected. Replicate with Fredrick, Rating III - Test record 100005 should show up

3.Issue with PDF view - Header name/Title and table broken into pages.

**Comment by TaraF** [comment]
@ladejobi  --these are fixed. please test.

**Comment by ladejobi** [comment]
Issues 1 is fixed. Issue 2 and 3 still persisting

**Comment by ladejobi** [comment]
New issues:
1. System does not always populate the County and SHA Rating fields on reports
2. Filter  Data returned on report by:
- Facility status = Existing
- Owner Name = SHA owned (including joint SHA fields, wild card that includes anything that has ‘SHA’)

**Comment by TaraF** [comment]
new items updated:
1. System should always be populating the headers now on report
2. Data is filtered on existing, and anything that includes SHA in owner

old items fixed:
1. all available data is shown
2. PDF issue is fixed

**Comment by ladejobi** [comment]
All issues fixed. @TaraF we should add a text at the bottom of the report stating something to the fact that only records with are status of Facility status = Existing and Owner Name = SHA owned are included in the report.

**Comment by TaraF** [comment]
note included at the top. please test in kci dev.

**Comment by ladejobi** [comment]
fix verified
