### ISSUE TITLE
General Tab Updates - Date Constructed 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#29]
a.	**Date Constructed**  
•	Maintain as a date field on the back end free text on the UI
•	When user enters a year value, the system should default field to Jan 1st of that year on the UI and back-end i.e 1/1/2017

**Comment by TaraF** [comment]
@mohsinkar , the backend is already a date field. Can you update from flex in to take "2017" or whatever 4 digit and make it "1/1/2017" when you write it back?

**Comment by ladejobi** [comment]
Fix validated.
