### ISSUE TITLE
Location manager selection  - returning web service error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#3]
After executing a search selection and choosing a record from the location manager the system returns the web service error below:
![image](https://user-images.githubusercontent.com/8458252/30997220-44145d8c-a494-11e7-9fcd-1d7a15268c9a.png)
The system also returned this error after user initiated the Add workflow and clicked on the map to draw a polygon.

**Comment by TaraF** [comment]
Hi Feyi,  In both of these cases, the service that is breaking is here:  http://vm-adwdev/NpdesServices/GetCandidatesByPoint?browsernocache=Fri%20Sep%2029%2014%3A10%3A21%20GMT%2D0400%202017&format=xml&XCoord=1414992%2E9445728017&YCoord=642274%2E7698844154 

That is a service that has been used historically, and no changes were made to it.  I believe it may have to do with some missing data at KCI, as it is working in both SHA dev and prod and no new changes should effect it.  

Please defer until we can migrate and test updates in SHA dev.  Thanks!

**Comment by ladejobi** [comment]
This issue is not occurring in SHA Dev.
