### ISSUE TITLE
General Tab - System Logic and Attributes Updates

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#30]
1. The system should present these fields as optional 
•	For TMDL
•	JPA

2.  Update the JPA field to:
o	Include a blank value as a domain
o	 WOA domain to WUS

**Comment by TaraF** [comment]
@mohsinkar  - I have updated #2 on the arc domain side.  You will need to update all domains table.  For #1, I am not enforcing a value in the service, you should be able to pass null, I think the restriction is on the flex side -- you should be able to update to not enforce they fill out those fields. Let me know if you have issues.

**Comment by ladejobi** [comment]
@mohsinkar Fixes validated. See issues identified;
1. The system does not successfully execute the edit workflow. it returns an error stating "The SWMFAC has not been saved"
2. Remove the asterisks on the JPA and For TMDL field
3. @TaraF the system is enforcing Date construed and As-Built fields as required. This was not specified in the requirements, is this logic correct?

**Comment by ladejobi** [comment]
@mohsinkar I confirmed with Stakeholders the Date construed and As-Built fields under the general tab should not be required.

**Comment by ladejobi** [comment]
Fix for No. 1 and 2 above have been tested. 

No.3 issue has not been fixed. The system should no longer enforce **Date constructed** and **As-Built Certification Date** fields under the general tab as required.

**Comment by ladejobi** [comment]
The system commits edits made in the Gen tab however it still shows the error requesting user to complete all required fields and when user tries to exit results tab presents a discard edit pop up.

**Comment by ladejobi** [comment]
@mohsinkar i know you're still working on this but be mindful we persist req that was already there. I see it's missing now. See below.

![image](https://user-images.githubusercontent.com/8458252/34841986-18bce67c-f6d8-11e7-9b32-e751e2b6d641.png)

**Comment by ladejobi** [comment]
@TaraF related to email from Mohsin

**Comment by ladejobi** [comment]
The Date constructed error has been fixed. The only issue that remains with this bug is the edit gen info workflow error

**Comment by ladejobi** [comment]
The system is still persisting new fields in added in Gen tab as required. Please investigate issue for both edit and add workflow

**Comment by mohsinkar** [comment]
@Tara the Update service http://vm-adwdev/NpdesServices/UpdateSWMFAC 
should return globalid  facilityid swmfacno currently the service is called and it is not performing the update and returning the above 3 values

**Comment by TaraF** [comment]
@mohsinkar  -- service fix. see email with successful fiddler session. please make sure parameters are being pulled into UI correct for display as well as being written to service.

**Comment by ladejobi** [comment]
fix validated
