### ISSUE TITLE
Inspection Tab - Inspection table - Apply Hover Function 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#31]
Apply the hover function on lengthy field names in the inspection table that are not fully visible to user.

**Comment by TaraF** [comment]
@mohsinkar this was requested by the main stakeholder at the last meeting we had. It is specifically for the FIELD name column.  I indicated that it may become annoying to user, but they would like to see it first.  Can you please add?

**Comment by ladejobi** [comment]
Unable to validate fix. Hover function not present.

**Comment by ladejobi** [comment]
@mohsinkar the hover function is not been applied to the FIELD name column. It works only for the VALUE column. Please update

**Comment by ladejobi** [comment]
Bug fixed
