### ISSUE TITLE
Rating Table - Update Rating ID Field

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#32]
Complete these (2) updates on the Rating ID field:
1. Update the Rating ID to a unique 36-digit GUID that contains text and numbers. 
2. Remove the Ratings ID field from the UI

**Comment by TaraF** [comment]
1. is done.  2. - @mohsinkar  can you remove from UI?

**Comment by ladejobi** [comment]
fix validated
