### ISSUE TITLE
Ratings Table - Update Field

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#33]
Update “Contract” field  to Anticipated Contract on the backed only

**Comment by TaraF** [comment]
@ladejobi  -- my notes say on the front end only -- and Kerry confirmed in her email.  We will leave the back end "CONTRACT".   The label on the front end just needs to say "Anticipated Contract".  @mohsinkar -- can you make this update?

**Comment by ladejobi** [comment]
@TaraF is correct, update should be UI only.

**Comment by ladejobi** [comment]
fix validated
