### ISSUE TITLE
Maint tab - Filter not working as per design specs -Ref wireframes

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#38]
When the user select to filter by rating date the system should return the rating date as a drown menu and the inspection date as a read only text field. The system will populate the inspection field upon user selecting a rating record. Same workflow applies to the filter by inspection date.

**Comment by mohsinkar** [comment]
@ladejobi is it necessary to have a TextField can we keep it as a disable dropdown. Functionality is not impacted.

**Comment by ladejobi** [comment]
@mohsinkar Yes if doing i otherwise will create a high level of effort. The Filter is currently not working a fully expected. It disables fields even when there's a rating associated

**Comment by ladejobi** [comment]
Bug fixed
