### ISSUE TITLE
Maint Tab - Attribute Name - Update

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#45]
Update the following fields within the maintenance tab as follows on the UI and Backend:
- WORK_ORDER_INITIATED to **WORK_ORDER_ASSIGNED**
- WORK_ORDER_INITIATION_DATE to **WORK_ORDER_ASSIGNED_DATE**

**Comment by mohsinkar** [comment]
@ladejobi UI Updated

**Comment by ladejobi** [comment]
UI update validated. @TaraF confirm when backend update is complete and we can close out bug

**Comment by TaraF** [comment]
@ladejobi  I thought we agreed that this was just an alias update (to UI only) and we would NOT change the backend field name.  My last correspondence with Kerry indicated that was her preference as well.  Also, the DB we received from PROD had it as original.  I believe the stakeholder was only concerned about alias in UI.

**Comment by ladejobi** [comment]
@TaraF ok great. I'll close out the bug
