### ISSUE TITLE
General Tab- Field updates - Missing 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#5]
The requirement calls for the system to update the General Tab as follows:             
(i) Date Constructed - Date field: Req not met                                                                                                     
ii) As Built Cert Date - Date field: Req not met

**Comment by mohsinkar** [comment]
@ladejobi 4 digit year based on requirement doc

**Comment by ladejobi** [comment]
agree with @mohsinkar this should be a 4 digit year field. Requirement satisfied.
