### ISSUE TITLE
HIGH Priority Fix - Insp/Rat and Maint Tab error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#54]
The  inspection and associated rating records in the Insp/rat tab does not match the record been displayed in the maint tab. 
![image](https://user-images.githubusercontent.com/8458252/34844052-31be1b2c-f6de-11e7-8f3d-e2ee2686c0d4.png)

**Comment by mohsinkar** [comment]
@ladejobi please verify this not able to replicate this issue.

**Comment by ladejobi** [comment]
@mohsinkar this an issue, replicated it on several records; 030020, 030001, 030020

**Comment by ladejobi** [comment]
Bug fixed, issue of duplicate records is due to Ratings data.
