### ISSUE TITLE
Search - Refresh error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#55]
After user executes a search and repeats another search the system does not refresh and clear out the previous search results in the Result tab (Tab sections only)

**Comment by ladejobi** [comment]
I'm still encountering this issue. The system does not refresh the results tab after user executes a new search.

**Comment by ladejobi** [comment]
@mohsinkar issue  is still occurring. the system defaults back to the tab user was when a new search is executed. See screenshots below, update system to default back to the Gen tab, just like it would with the initial search.

![image](https://user-images.githubusercontent.com/8458252/34920693-7f983fb8-f944-11e7-9945-ae4e0503fdc3.png)

**Comment by mohsinkar** [comment]
@ladejobi Defaulting to general tab is new this was never part of the functionality all tabs retain previous selection. 

I will update reset buttons in inspection tab

**Comment by ladejobi** [comment]
@mohsinkar you are correct. Validated the workflow in PROD.

**Comment by ladejobi** [comment]
Bug fix validated
