### ISSUE TITLE
Maint Tab - Add workflow - Date Field /scrollable bar error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#57]
1.When user executes add maint workflow and commits record to the database, the system returns incorrect date values and does not persist some date fields for the record entered by user.  
2. The values on the date fields appear and disappear as user moves the scrollbar bar.

**Comment by ladejobi** [comment]
@mohsinkar this is still an issue.Please investigate

**Comment by ladejobi** [comment]
@mohsinkar @TaraF to review and resolve

**Comment by TaraF** [comment]
@ladejobi , @mohsinkar :  all fields are being written correctly on insert maint (with exception of anticipation date -- see bug #62 -- Mohsin will need to fix how it is being passed in), and the get maint service is returning all values correctly, but they are being displayed incorrectly in UI.  I'm not sure @mohsinkar -- but thinking some of main values are getting stored from previous when being displayed.

**Comment by ladejobi** [comment]
BUG FIXED!
