### ISSUE TITLE
Rating and Maint Edit Workflow - Date Field Error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#62]
@mohsinkar there's an issue with the date fields we need to investigate. It's impacting both the Insp/Rat and Maint Tab. 

1) Rating Workflow - When user completes a date field edit the system doesn't always persist the value entered by user, it changes the value of all the Date fields to a random date including the one entered by user.
2) Maint Workflow - When user completes any Maint field edit the system now persist the changes however it's changing other date fields on the fly to random date values once user commits the changes

**Comment by ladejobi** [comment]
@mohsinkar @TaraF to review and resolve

**Comment by TaraF** [comment]
@ladejobi  -- lets walk thru #1 @930. I cannot replicate this AM.

@mohsinkar -- #2,  there two problems with this that I can see. Please see email referencing this bug for details.

**Comment by ladejobi** [comment]
The No.1 issue has been fixed.

**Comment by ladejobi** [comment]
I just tested again @mohsinkar @TaraF the No.1 item is still an issue. 
 - The system overrides date value entered by user with a different value after user complete an edit a rating date or QR date workflow.

**Comment by ladejobi** [comment]
@TaraF @mohsinkar issues are still occurring
**Maintenance Tab** - System changes dates on the date fields on the fly as users scroll up and down. 
**Rating Tab** - Replicate by editing the Rating Date field and Save. The system will either persist the rating date edit and erroneously change the QR date field OR erroneously change the values for both the Rating Date and QR date fields. @TaraF will you investigate further or any recommendation to Mohsin for fix?

**Comment by ladejobi** [comment]
BUG FIXED!Pheww!
