### ISSUE TITLE
Delete Rating Workflow - Not functional 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#65]
The delete rating function is not working. The system does not delete record from the UI.

**Comment by mohsinkar** [comment]
@TaraF please check the service

**Comment by TaraF** [comment]
@mohsinkar, @ladejobi this is fixed.

**Comment by ladejobi** [comment]
Bug fix validated.

**Comment by ladejobi** [comment]
@mohsinkar @TaraF The system does not delete the date fields (rating and QR) when user executes the delete rating workflow. However the system does delete the record from the Maint tab. I suspect the record is been deleted from the database but not on the UI. @mohsinkar pls review for resolution and assign to Tara if appropriate.

**Comment by ladejobi** [comment]
Issue is still persisting @TaraF can you take a look?

**Comment by ladejobi** [comment]
@TaraF I encounter issue when I execute the delete workflow. Would you like us to do a screen share?

**Comment by TaraF** [comment]
@mohsinkar -- please take a look at this on flex side and fix. I confirmed things are being deleted on the back end as they should be. 
You may need to completely set the datagrid.dataprovider to an empty AC to make sure it is completely clearing out all fields after delete.

**Comment by ladejobi** [comment]
fix verified
