### ISSUE TITLE
Map Not interactive

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#66]
The map is not interactive when user makes a search selection just noticed after i did a test in PROD  @TaraF is this a bug or will it work fine when we deploy to SHA?

**Comment by TaraF** [comment]
Sorry, didn't have time to finish pushing the new MXD to the UI....if I can get to this AM with deploy to SHA, will do.

**Comment by ladejobi** [comment]
Map working fine in SHA Dev
