### ISSUE TITLE
Ratings Tab - Delete Ratings on Old inspections - Requirement not Met 

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#7]
The system allows user to initiate delete workflow on ratings associated to old inspections, however the requirement call for this not to be permitted, only ratings associated to current inspections can be deleted. 

@mohsinkar  I've updated this bug, just spoke with Tara, the ratings associated to old inspections should be **view only, with all buttons disabled.** The system should not allow user to add, edit or delete ratings associated to old inspections.

**Comment by ladejobi** [comment]
@mohsinkar bug is partially fixed. The system still allows user to enter rating information for old inspections Disable all rating fields associated to old inspections, it should be view only.

**Comment by ladejobi** [comment]
@mohsinkar the initial bug has been partially fixed, but there are additional (2) new issues.
1. Grey out the label names for rating on old inspections only the fields are currently greyed out 
2.The system no longer allows user to edit/add rating to the latest inspection. This function was working prior.
3. The Rating Date and QR Date fields do not show the date fields on both old and new ratings.

**Comment by ladejobi** [comment]
No.1 issue above has been resolved.
No. 2 issue still persisting - The Rating Date and QR Date fields do not show the date fields on the old ratings.

**Comment by TaraF** [comment]
@ladejobi -- I believe this is showing blank because there is no data to display.  Let's hold this bug to take a look once I load in the back data from Kerry/ Holly.  I will plan on doing this tomorrow so you can review it again.

**Comment by ladejobi** [comment]
The date fields are visible now however they are shaded out.
![image](https://user-images.githubusercontent.com/8458252/34910041-5ed93c56-f87b-11e7-9ef6-6c80b258b90e.png)

**Comment by ladejobi** [comment]
Bug fix tested and validated
