### ISSUE TITLE
Gen Tab - Domain error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#71]
Add a space to the "Not Applicable" domain for JPA field in the Gen tab.

**Comment by mohsinkar** [comment]
domain is already set to "Not Applicable"

**Comment by ladejobi** [comment]
@mohsinkar domain set at "NotApplicable" change to "Not Applicable" Add a space in between the words.

**Comment by ladejobi** [comment]
Fix verified
