### ISSUE TITLE
Maint Tab - SHA Book - field error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#72]
System returns an IO error when user populates the SHA book in this format (17-PR-0141-02). Increase or update the field length ( looks like 13) to support this format.

**Comment by ladejobi** [comment]
Database has a 10 character limit needs to be increased. Feyi will confirm with Kerry and update

**Comment by ladejobi** [comment]
@TaraF spoke with Kerry to make it 20 character field. Stakeholders will enter 13 character now but this gives flexibility in case their process changes

**Comment by ladejobi** [comment]
@TaraF don't think you worked on this yet. I'm still encountering the error.

**Comment by TaraF** [comment]
this field has been updated to a length of 20 in KCI dev.  Please test.

**Comment by ladejobi** [comment]
Fix verified
