### ISSUE TITLE
Existing Function - Reserve SWMFAC - Broken

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#75]
The reserve SWMFAC function is not working in  KCI and SHA DEV. IIt's working as expected in production.

**Comment by ladejobi** [comment]
@Mohsin update URL that are returning errors and assign to Tara.

**Comment by mohsinkar** [comment]
@TaraF http://vm-adwdev/NpdesServices/GetNextSWMFACNums?County=01&format=xml&UserId=KCI%5CMOHSIN%2EKARIM&browsernocache=Mon%20Jan%2029%2008%3A48%3A21%20GMT%2D0600%202018&Limit=1

**Comment by TaraF** [comment]
@ladejobi  this is working in SHA dev now. Please test.

**Comment by ladejobi** [comment]
@TaraF  this is partly working in SHA Dev. The system returns the correct value in the widget after executing the swmfac reserve however it returns an error in the report generated in a new browser. see screenshots. This function is working in Prod

![image](https://user-images.githubusercontent.com/8458252/35587244-3c2d5b44-05cb-11e8-9052-0912bee6ead0.png)

**Comment by ladejobi** [comment]
Reserve SWMFAC function partly working in SHA Dev, returns values in widget but runtime error in new browser. Workaround is to maintain/persist existing code for function when we deploy to prod. Functionality working in PROD.

**Comment by TaraF** [comment]
Agreed, the services and flex code are returning correctly, it just appears that the reporting service is broken in SHA dev.  At this point do not want to waste time trying to fix, when we know it is working correctly in prod and we have made no changes to it. 

Let's double check/verify after pushing to prod.

**Comment by ladejobi** [comment]
functionality working in production after push
