### ISSUE TITLE
Existing Function - Import - Broken in SHA DEV

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#76]
The existing Impot function is broken in KCI and SHA Dev but working in Production. Attached is a  sample document to  replicate Import workflow.
[SHA_SWM_Fac_Number_Request_BS-R-8.2.pdf](https://github.com/kcigeospatial/SWMFAC-Enhancements/files/1665391/SHA_SWM_Fac_Number_Request_BS-R-8.2.pdf)

**Comment by mohsinkar** [comment]
@ladejobi thi is functional on KCI Dev

**Comment by ladejobi** [comment]
@mohsinkar the second drop down is not populating fields

**Comment by ladejobi** [comment]
@mohsinkar will send Tara to service call that relates to bug and Tara will investigate

**Comment by mohsinkar** [comment]
@TaraF 

http://vm-adwdev/NpdesServices/GetPDFInformation?format=xml&browsernocache=Mon%20Jan%2029%2008%3A46%3A56%20GMT%2D0600%202018&Path=C%3A%5Cinetpub%5Cwwwroot%5CNpdesUpload%5Cfiles%5Cupload%5F636528339865374657%2Epdf

**Comment by TaraF** [comment]
@ladejobi , @mohsinkar    this contract (WO6355170) does NOT exist in KCI dev, but DOES exist in SHA dev and SHA prod.  Hope that helps. Services are returning correctly, I don't see any errors here.

**Comment by ladejobi** [comment]
Import function not working in SHA Dev, returns IO error. Workaround is to maintain/persist existing code for function when we deploy to prod. Functionality working in PROD.

**Comment by TaraF** [comment]
Sent email to John S. to confirm, but fairly positive this is due to the file written on SHA Dev, but service hosted on SHA PROD and it cannot see the file to read it correctly. 

We will wait for John's confirmation/response, and expect to push to prod as is.  We will need to verify after pushing to PROD.

**Comment by ladejobi** [comment]
Function working in prod after push
