### ISSUE TITLE
SWMFAC data loading error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#77]
The system shows an infinity loading message when user searches for some BMP features, replicate with 060537. This issue is occurring in KCI and SHA Dev but not production.

**Comment by mohsinkar** [comment]
@ladejobi data issue the SWMFAC not associated with a polygon

**Comment by ladejobi** [comment]
@TaraF please confirm if data is missing for this SWMFAC.

**Comment by ladejobi** [comment]
Fix validated
