### ISSUE TITLE
SWMFAC Summary Report - attribute typo

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#79]
Change the field “Feature Status Existing” to “Feature Status”
![image](https://user-images.githubusercontent.com/8458252/35410271-e34e3b60-01e2-11e8-8a6f-08bc7a04c026.png)

**Comment by TaraF** [comment]
fixed. please test in KCI dev.

**Comment by ladejobi** [comment]
fix verified
