### ISSUE TITLE
SWMFAC County and Rating Report - Returning Incorrect values

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#85]
The system is not returning accurate records in the SWMFAC Details by County and Rating Report. The system is not returning the most recent inspection and rating associated to the SWMFAC

**Comment by TaraF** [comment]
This is fixed. Please test in KCI dev.

**Comment by ladejobi** [comment]
@TaraF  the report is not returning the most recent insp and rat. See screenshot below for 010038. Most recent insp/rating is 6/11/2016 and 11/01/12 but reports shows an older record


![image](https://user-images.githubusercontent.com/8458252/35585910-3e075f7c-05c7-11e8-9958-9661baa86379.png)

**Comment by TaraF** [comment]
@ladejobi  the code is correct.  you selected Allegany county, SHA Rating = I.   what you have highlighted in red there is for a SHA Rating of II.

**Comment by ladejobi** [comment]
Oh @TaraF youre right. Ok this is good.

**Comment by ladejobi** [comment]
Fix verified
