### ISSUE TITLE
SWMFAC Summary Report - Error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#86]
The system returns incorrect values in the Rating Information section. We are showing all historical/new rating records in the Maint tab. So Ratings records in Maint tab = Ratings returned in report. Replicate with 030005.

![image](https://user-images.githubusercontent.com/8458252/35542205-d6118018-052c-11e8-8862-51bcab42f238.png)

**Comment by TaraF** [comment]
This is fixed, please test in KCI dev.

**Comment by ladejobi** [comment]
fix verified
