### ISSUE TITLE
Data lag loading Error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#89]
The system does not refresh and load data in the tab section after user selects a record from the location manager. In some cases the system would load the last record selected after user selects a new record. To replicate, select different records in the location manager to confirm. This issue is not occurring in KCI Dev

![image](https://user-images.githubusercontent.com/8458252/35838323-c0daa382-0ab8-11e8-977f-adb776f545f4.png)

**Comment by TaraF** [comment]
@ladejobi , @mohsinkar  -- I tested in KCI dev and confirmed that the same functionality is happening in KCI.  I did a search by Baltimore county, and choose records straight down the line one by one.  It is holding on to previous info in the grid, but the services in fiddler are returning the correct information. 

This needs to be fixed on the flex side and confirmed in KCI dev.

**Comment by ladejobi** [comment]
Bug fixed
