### ISSUE TITLE
Docs Tab - Links - System failed to open PDF

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#9]
The system does not open the PDF in a new browser after user clicks on a link within the Docs tab. The system open a new browser and returns a server error message.
![image](https://user-images.githubusercontent.com/8458252/31019305-36a47cf4-a4fd-11e7-9cfc-76a70b7aebbe.png)

**Comment by mohsinkar** [comment]
The data is not available on the KCI dev so link will show file not found error 
the requirements were to open links in new tab

**Comment by ladejobi** [comment]
I'll test function in SHA Dev

**Comment by ladejobi** [comment]
Validated in SHA Dev
