### ISSUE TITLE
Export Function - Working but system returning error message

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#90]
The export function is functioning in SHA Dev (not functioning in KCI Dev) however system returns an IO error pop up message and a runtime error in a new browser after user executes the export workflow. Errors not occurring in production

**Comment by TaraF** [comment]
@ladejobi , @mohsinkar  --we need to make sure the export is working in KCI dev first. this heavily relies on flex for a large portion of it.  I didn't catch in our conversation yesterday it wasn't working in KCI.

**Comment by ladejobi** [comment]
Bug fixed in SHA Dev
