### ISSUE TITLE
SHA Book - Field length error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#92]
Update SHA Book field length in SHA DEV and PROD. @TaraF work with Jake to update in SHA DEV

**Comment by TaraF** [comment]
@ladejobi  -- this has been updated to a length of 20, and Jake has restarted the service.  Please test in SHA dev.

**Comment by ladejobi** [comment]
Fix validated in Dev. Ready for push to PROD

**Comment by ladejobi** [comment]
Fix validated in prod
