### ISSUE TITLE
Delete SWMFAC workflow error

### ISSUE THREAD

**Issue by ladejobi** [kcigeospatial/SWMFAC-Enhancements#94]
@mohsinkar the system is not clearing out the tab section after user executes a delete SWMFAC workflow. please fix in KCI Dev

**Comment by ladejobi** [comment]
@mohsinkar the system deletes info on all tabs except the Insp/Rating, Maint and Doc tab

**Comment by ladejobi** [comment]
Bug fix verified. Ready to push to SHA DEV

**Comment by TaraF** [comment]
pushed to SHA dev. Please test.

**Comment by ladejobi** [comment]
Fix validated in Dev. Ready for push to Prod.

**Comment by ladejobi** [comment]
Validated in Prod
